# Generated by Django 4.2.4 on 2023-09-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_savings_saving_rename_expense_spending_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
