export const GET_WALLET_LIST_SUCCESS = 'GET_WALLET_LIST_SUCCESS'
export const GET_WALLET_LIST_FAIL = 'GET_WALLET_LIST_FAIL'

export const GET_WALLET_USER_LIST_SUCCESS = 'GET_WALLET_USER_LIST_SUCCESS'
export const GET_WALLET_USER_LIST_FAIL = 'GET_WALLET_USER_LIST_FAIL'

export const SET_WALLET_NULL = 'SET_WALLET_NULL'

export const GET_WALLET_SUCCESS = 'GET_WALLET_SUCCESS'
export const GET_WALLET_FAIL = 'GET_WALLET_FAIL'


