export const GET_SAVING_LIST_SUCCESS = 'GET_SAVING_LIST_SUCCESS';
export const GET_SAVING_LIST_FAIL = 'GET_SAVING_LIST_FAIL';

export const GET_SAVING_SUCCESS = 'GET_SAVING_SUCCESS';
export const GET_SAVING_FAIL = 'GET_SAVING_FAIL';

export const SET_SAVING_NULL = 'SET_SAVING_NULL';