export const GET_SPENDING_LIST_SUCCESS = 'GET_SPENDING_LIST_SUCCESS';
export const GET_SPENDING_LIST_FAIL = 'GET_SPENDING_LIST_FAIL';

export const GET_SPENDING_SUCCESS = 'GET_SPENDING_SUCCESS';
export const GET_SPENDING_FAIL = 'GET_SPENDING_FAIL';

export const SET_SPENDING_NULL = 'SET_SPENDING_NULL';